### PR TITLE
Fix/70 locale a11y

### LINKED ISSUE #70: Can't tab to locale search field
1. Load the home page and start tabbing through the items until you reach the `Swag` link
2. Hit `tab` one more time, which will take you to `#select2-wp20-locale-switcher-container`
3. Hit `enter` to open the menu
4. The focus is on the currently selected locale, and you can `arrowup` / `arrowdown` to move between them
5. Hit `shift-tab` to go to the search field, and it will close the list and take you back to `#select2-wp20-locale-switcher-container` instead of moving the focus to the search `input`.

### PR DESCRIPTION
**Pull request by adamwoodnz**
Fixes #70 

Branches off the initial commits in #71 with styles to get the autocomplete as close as possible to the designs and the current switcher on prod

#### Desktop
| Focus | Cleared | Search |
|-|-|-|
| Screen Shot 2023-04-27 at 1 01 47 PM | Screen Shot 2023-04-27 at 1 02 05 PM | Screen Shot 2023-04-27 at 1 02 21 PM |

#### Mobile (emulated)
| Focus | Cleared | Search |
|-|-|-|
| Screen Shot 2023-04-27 at 1 05 36 PM | Screen Shot 2023-04-27 at 1 05 49 PM | Screen Shot 2023-04-27 at 1 06 02 PM |

#### Mobile

The autoselected input text isn't a very nice experience on my Chrome for Android, as the contextual options are displayed, but I guess that is expected, and enables the input to be cleared with one tap of delete:

### CODE REVIEW

File: wp-content/mu-plugins/assets/locale-switcher.js [hunk 1]
```diff
@@ -16,26 +16,105 @@
...
-			app.$switcher.on( 'change', function() {
-				$(this).parents( 'form' ).submit();
+				make sure escaped
+				*/
+
+				// { templates: { inputValue, suggestion } } to let search by endonym and english name
+					// make sure escaped
+
+
+				placeholder: 'Search languages...',
```
Comment (adamwoodnz) [inline wp-content/mu-plugins/assets/locale-switcher.js]: String needs translation. From current UI:

File: wp-content/themes/twentyseventeen-wp20/header.php [hunk 2]
```diff
@@ -27,7 +27,8 @@
 						<div class="wrap wrap-wide">
 							<?php get_template_part( 'template-parts/header/navigation', 'top' ); ?>
 							<?php Locales\locale_switcher(); ?>
-							<div class="navigation-top-menu-container" data-placeholder="<?php esc_attr_e( 'Search languages...', 'wp20' ); ?>"></div>
+							<!-- data-placeholder="<?php esc_attr_e( 'Search languages...', 'wp20' ); ?>" -->
```
Comment (adamwoodnz) [inline wp-content/themes/twentyseventeen-wp20/header.php:30]: Seems like this isn't required with the `label .screen-reader-text` and [placeholder in JS](https://github.com/WordPress/wp20.wordpress.net/pull/93/files#diff-c86a86024c4de465cc9785b050a285506c9b64f456cc4c7b923c48345cfc021eR85)

File: wp-content/mu-plugins/assets/locale-switcher.js (hunk 1 above)
Comment (adamwoodnz) [reply wp-content/mu-plugins/assets/locale-switcher.js]: Ah maybe it should use the string here https://github.com/WordPress/wp20.wordpress.net/pull/93/files#diff-1368bd0d70766b64532fd35e145bb6e6cea9b47f3297d37027f10d2f8865e763R30

Comment (adamwoodnz) [reply wp-content/mu-plugins/assets/locale-switcher.js]: Done in https://github.com/WordPress/wp20.wordpress.net/pull/93/commits/54d4216fdcbb7da69b8b38e14e36b53239afe91c

Comment (iandunn) [reply wp-content/mu-plugins/assets/locale-switcher.js]: Yeah, that looks like a good approach 👍🏻

File: wp-content/themes/twentyseventeen-wp20/style.css [hunk 3]
```diff
@@ -696,132 +699,94 @@ body:not(.title-tagline-hidden) .site-branding-text {
...
 
-@media screen and (max-width:48em) {
-	.wp20-locale-switcher-container.is-toggled {
-		background: var(--wp20--color--active-menu);
+@media screen and (min-width: 769px) {
+	.autocomplete__wrapper {
+		display: flex;
+		flex-direction: column;
+		align-items: flex-end;
+		z-index: 1;
```
Comment (iandunn) [inline wp-content/themes/twentyseventeen-wp20/style.css:739]: I added this in 385a511 because the input/ul was hidden on desktops when clicking into it:

Screenshot 2023-05-03 at 6 32 05 AM

i'm not sure if it'll be needed after other changes though

File: wp-content/themes/twentyseventeen-wp20/style.css [hunk 4]
```diff
@@ -696,132 +699,94 @@ body:not(.title-tagline-hidden) .site-branding-text {
...
-	}
-
-	.navigation-top-menu-container .select2-dropdown {
-		border: 1px solid var(--wp20--color--border) !important;
-	}
-}
-
-.wp20-locale-switcher-container {
+.wp20-locale-switcher-container form {
 	position: absolute;
```
Comment (iandunn) [inline wp-content/themes/twentyseventeen-wp20/style.css]: This makes it so that `.site-content-contain` is covered by the dropdown on mobile:

Screenshot 2023-05-03 at 7 44 56 AM

On `trunk` it pushes the content down though:

Screenshot 2023-05-03 at 7 47 46 AM

I don't see a good way to fix that. One problem I kept running into with these PRs is that the menu DOM structure is different than the locale list structure. The menu toggle button is a separate element from the menu itself, while the switcher "toggle" and dropdown are all contained in a single element.

Another part might be that [Accessible Autocomplete doesn't add classes for the current state](https://github.com/alphagov/accessible-autocomplete/issues/384). The `input` can be styles by matching `aria-expanded=true`, though; and the `ul` with `.autocomplete__menu--visible`.

File: wp-content/themes/twentyseventeen-wp20/style.css [hunk 5]
```diff
@@ -502,13 +502,16 @@ body:not(.title-tagline-hidden) .site-branding-text {
...
 .navigation-top {
-	position: relative;
 	z-index: 20;
 	background: #fff;
 	border: unset;
 	font-size: 14px;
 }
 
+.navigation-top .wrap {
+	display: flex;
```
Comment (iandunn) [inline wp-content/themes/twentyseventeen-wp20/style.css:512]: This works well for the desktop, but I noticed this on mobile:

Screenshot 2023-05-03 at 8 22 17 AM

I haven't come up with a good fix.

File: wp-content/themes/twentyseventeen-wp20/style.css [hunk 6]
```diff
@@ -696,132 +699,94 @@ body:not(.title-tagline-hidden) .site-branding-text {
...
+	background-repeat: no-repeat;
+	background-size: 13px;
+	background-position: calc(100% - 20px) center;
+	padding-top: 13px;
+	padding-bottom: 13px;
+	line-height: 1.4;
 }
 
-.wp20-locale-switcher-container .select2-container--open .select2-selection--single .select2-selection__rendered {
+.autocomplete__hint {
```
Comment (iandunn) [inline wp-content/themes/twentyseventeen-wp20/style.css:784]: I'm not sure why, but the first word isn't capitalized in the hint, even though it is in the raw data and in the dropdown:

Screenshot 2023-05-03 at 8 25 19 AM

It's odd because the text doesn't seem to show up in the DOM, and it's not set via CSS `content` either 🤔 I checked the Autocomplete source and it wasn't obvious there.

I don't think it's related to any of the styles, and it was happening in #71 too.

`text-transform: capitalize` works in some cases, but would be wrong in ones like `Español De Colombia` where the `De` should be lowercase.

We are using the hint in an unintended way in order to match the design, but I'm not sure why that'd be related 🤷🏻‍♂️

**Review by iandunn — COMMENTED** [review]
I cleaned up some of my WIP JS, added translations, etc. I'm running into a few CSS issues that I haven't found solutions for, though.

File: wp-content/themes/twentyseventeen-wp20/style.css (hunk 4 above)
Comment (adamwoodnz) [reply wp-content/themes/twentyseventeen-wp20/style.css]: I think this is fixed now. I've added a wrapper to the nav menu so that it behaves more like the locale one. Try it out.

File: wp-content/themes/twentyseventeen-wp20/style.css (hunk 5 above)
Comment (adamwoodnz) [reply wp-content/themes/twentyseventeen-wp20/style.css:512]: Should also be fixed by the new wrapper.

File: wp-content/themes/twentyseventeen-wp20/style.css (hunk 6 above)
Comment (adamwoodnz) [reply wp-content/themes/twentyseventeen-wp20/style.css:784]: I only get lowercase when I've entered lowercase in the input.

Looks like it might be this line, where the input text replaces the start of the option https://github.com/alphagov/accessible-autocomplete/blob/main/src/autocomplete.js#L452

`hintValue` is bound here https://github.com/alphagov/accessible-autocomplete/blob/main/src/autocomplete.js#L490

Comment (iandunn) [reply wp-content/themes/twentyseventeen-wp20/style.css:784]: Ah, good find. Yeah, `jQuery( '.autocomplete__hint' ).val()` shows the value, but FF/Chrome inspectors don't 🤷🏻‍♂️ 

Doesn't look like anything we can change easily, so I'd say it's just a quirk, and not worry about it 👍🏻 

If we really have to I guess we could set up a mutation observer to overwrite it w/ the correct capitalization, but that may have a11y consequences, etc. I'm sure there's some reason they're doing the `substr` bit. I guess if we have to do that, it'd be better to just add our own custom element for sighted users, and leave the hint hidden for screen readers. The observer could copy the hint value into the custom element.

File: wp-content/themes/twentyseventeen-wp20/style.css (hunk 5 above)
Comment (iandunn) [reply wp-content/themes/twentyseventeen-wp20/style.css:512]: Good idea, looks great 👍🏻

**Review by iandunn — APPROVED** [review]
Great work, this is looking good in my tests 👍🏻
