### PR TITLE
Fix a11y

### LINKED ISSUE #11: a11y audit
Issues to be fixed listed in comments below.

### PR DESCRIPTION
**Pull request by adamwoodnz**
Fixes #11 

- [x] Replace H3 on Events list and Swag items with H2, to correct heading structure
- [x] Accessible names on map marker buttons
- [x] Accessible links in entry content using underline

Changing the color of the links didn't work; the issue is that the blueberry link text has insufficient contrast with the very dark grey body text, so going darker doesn't help, and going lighter (Blueberry 2 #7B90FF) results in insufficient contrast with the background.

### Screenshots

| What's on? | Single | Swag |
|-|-|-|
| Screen Shot 2023-04-12 at 12 41 40 PM | wp20 mystagingwebsite com_wapuu-coloring-giveaway-style-your-own-party-wapuu_(Desktop) | wp20 mystagingwebsite com_swag_(Desktop) |

### CODE REVIEW

File: wp-content/plugins/wp20-meetup-events/wp20-meetup-events.js [hunk 1]
```diff
@@ -361,6 +361,7 @@ var WP20MeetupEvents = app = ( function( $ ) {
 				name      : events[ markerID ].name,
 				time      : events[ markerID ].time,
 				url       : events[ markerID ].eventUrl,
+				title     : events[ markerID ].group,
```
Comment (adamwoodnz) [inline wp-content/plugins/wp20-meetup-events/wp20-meetup-events.js:369]: Group makes the most sense when tabbing around the map, as it typically includes the location name.

File: wp-content/themes/twentyseventeen-wp20/style.css [hunk 2]
```diff
@@ -93,8 +93,8 @@ p {
 
 h1,
 h2,
+h2.wp20-event-group,
 h3,
-h3.wp20-event-group,
```
Comment (iandunn) [inline wp-content/themes/twentyseventeen-wp20/style.css:97]: I think we might need to keep this for both the `h2` and `h3`, since the map markers also use it:

Screenshot 2023-04-12 at 10 20 48 AM

Screenshot 2023-04-12 at 10 20 09 AM

Or maybe the markers should also change to `h2`? They feel more like `h3` to me, though 🤔 

I wonder if instead we should add an `h2.screen-reader-text` above the map instead of changing the markers to `h2`? The same might apply to the list of events.

I don't have a strong opinion.

**Review by iandunn — APPROVED** [review]
This looks good to me 👍🏻 

The only thing that should probably change is the map marker styles. Whether or not to add the `h2.screen-reader-text` etc is a judgement call.

File: wp-content/themes/twentyseventeen-wp20/style.css (hunk 2 above)
Comment (adamwoodnz) [reply wp-content/themes/twentyseventeen-wp20/style.css:97]: Good point about those. I didn't have a popup open when I ran the scan. I'll try that and see what results.

Comment (adamwoodnz) [reply wp-content/themes/twentyseventeen-wp20/style.css:97]: > I wonder if instead we should add an h2.screen-reader-text above the map instead of changing the markers to h2? The same might apply to the list of events.

Yeah I like this approach. Updated the PR, works well:

Screen Shot 2023-04-13 at 8 56 45 AM

Comment (iandunn) [reply wp-content/themes/twentyseventeen-wp20/style.css:97]: Looks great 👍🏻
